name: Serverless Deployment Example

# Triggers
on:
  push:
    branches:
      - actions-** # feature branches
      - develop

# Specify what jobs to run
jobs:
  sls_deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1 

      - name: Set Branch name to $STAGE env var
        run: |
          BRANCH="$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          echo "BRANCH is $BRANCH"
          echo "::set-env name=STAGE::$BRANCH"

      # Install npm and it's dependencies
      - name: Install npm dependencies
        run: npm install

      # - name: Serverless Deploy          
      #   run: npx serverless deploy

      # sls deploy
      - name: Serverless deploy
        uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
        with:
          args: deploy
      
      # invoke the test function hello with no arguments
      - name: Serverless
        uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
        with:
          args: invoke -f hello
      
      # invoke the test function hello with arguments from test/name.json
      - name: Serverless Invoke
        uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
        with:
          args: invoke -f hello -p ./test/name.json

      # invoke the test function goodbye with arguments from test/name.json
      - name: Serverless Invoke
        uses: serverless/github-action@e17abe72d4969e86cb53576ade34e95c40362f0e
        with:
          args: invoke -f goodbye -p ./test/name.json


